version: '3.7'

services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: scj_https-portal_1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      CLIENT_MAX_BODY_SIZE: 1M
      HSTS_MAX_AGE: 60
      DOMAINS: 'www.speedcubing.or.jp => speedcubing.or.jp, speedcubing.or.jp -> http://nginx:8000'
      STAGE: 'production' # Don't use production until staging works
      # FORCE_RENEW: 'true'

  python:
    build: ./python
    container_name: scj_python_1
    ports:
      - "8001:8001"
    command: uwsgi --ini /code/uwsgi.ini
    volumes:
      - ./python/uwsgi.ini:/code/uwsgi.ini
      - ./python/src:/code
      - ./static:/static
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    sysctls:
      net.core.somaxconn: 40960
    depends_on:
      - db
