# Generated by Django 2.2.12 on 2020-11-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_community_posting_offer',
            field=models.BooleanField(default=False, verbose_name='宣伝申請許可'),
        ),
    ]
