# Generated by Django 2.2.24 on 2021-06-24 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="stripe_customer_id",
            field=models.CharField(
                default="", max_length=256, verbose_name="STRIPE_CUSTOMER_ID"
            ),
        ),
    ]
