# Generated by Django 2.2.24 on 2021-06-24 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_person_stripe_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeperevent',
            name='prepaid_price',
            field=models.IntegerField(default=0, verbose_name='事前決済料金'),
        ),
        migrations.AddField(
            model_name='feepereventcount',
            name='prepaid_price',
            field=models.IntegerField(default=0, verbose_name='事前決済料金'),
        ),
    ]
