# Generated by Django 2.2.12 on 2020-12-09 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201122_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='begin_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時刻'),
        ),
        migrations.AddField(
            model_name='round',
            name='end_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='終了時刻'),
        ),
        migrations.AddField(
            model_name='round',
            name='room_name',
            field=models.CharField(default='', max_length=64, verbose_name='会場名'),
        ),
    ]
