# Generated by Django 2.2.12 on 2020-12-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20201209_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scramble',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.IntegerField(verbose_name='大会ID')),
                ('event_id', models.SmallIntegerField(choices=[(1, '3x3x3 キューブ'), (2, '2x2x2 キューブ'), (3, '4x4x4 キューブ'), (4, '5x5x5 キューブ'), (5, '6x6x6 キューブ'), (6, '7x7x7 キューブ'), (7, '3x3x3 目隠し'), (8, '3x3x3 最少手数'), (9, '3x3x3 片手'), (10, 'クロック'), (11, 'メガミンクス'), (12, 'ピラミンクス'), (13, 'スキューブ'), (14, 'スクエア1'), (15, '4x4x4 目隠し'), (16, '5x5x5 目隠し'), (17, '3x3x3 複数目隠し')], verbose_name='イベントID')),
                ('round_id', models.IntegerField(verbose_name='ラウンドID')),
                ('group_id', models.CharField(max_length=4, verbose_name='グループID')),
                ('scramble', models.CharField(max_length=64, verbose_name='スクランブル')),
            ],
        ),
        migrations.AlterField(
            model_name='averagerank',
            name='event_id',
            field=models.SmallIntegerField(choices=[(1, '3x3x3 キューブ'), (2, '2x2x2 キューブ'), (3, '4x4x4 キューブ'), (4, '5x5x5 キューブ'), (5, '6x6x6 キューブ'), (6, '7x7x7 キューブ'), (7, '3x3x3 目隠し'), (8, '3x3x3 最少手数'), (9, '3x3x3 片手'), (10, 'クロック'), (11, 'メガミンクス'), (12, 'ピラミンクス'), (13, 'スキューブ'), (14, 'スクエア1'), (15, '4x4x4 目隠し'), (16, '5x5x5 目隠し'), (17, '3x3x3 複数目隠し')], verbose_name='イベントID'),
        ),
        migrations.AlterField(
            model_name='bestrank',
            name='event_id',
            field=models.SmallIntegerField(choices=[(1, '3x3x3 キューブ'), (2, '2x2x2 キューブ'), (3, '4x4x4 キューブ'), (4, '5x5x5 キューブ'), (5, '6x6x6 キューブ'), (6, '7x7x7 キューブ'), (7, '3x3x3 目隠し'), (8, '3x3x3 最少手数'), (9, '3x3x3 片手'), (10, 'クロック'), (11, 'メガミンクス'), (12, 'ピラミンクス'), (13, 'スキューブ'), (14, 'スクエア1'), (15, '4x4x4 目隠し'), (16, '5x5x5 目隠し'), (17, '3x3x3 複数目隠し')], verbose_name='イベントID'),
        ),
        migrations.AlterField(
            model_name='result',
            name='event_id',
            field=models.SmallIntegerField(choices=[(1, '3x3x3 キューブ'), (2, '2x2x2 キューブ'), (3, '4x4x4 キューブ'), (4, '5x5x5 キューブ'), (5, '6x6x6 キューブ'), (6, '7x7x7 キューブ'), (7, '3x3x3 目隠し'), (8, '3x3x3 最少手数'), (9, '3x3x3 片手'), (10, 'クロック'), (11, 'メガミンクス'), (12, 'ピラミンクス'), (13, 'スキューブ'), (14, 'スクエア1'), (15, '4x4x4 目隠し'), (16, '5x5x5 目隠し'), (17, '3x3x3 複数目隠し')], verbose_name='イベントID'),
        ),
        migrations.AlterField(
            model_name='round',
            name='event_id',
            field=models.SmallIntegerField(choices=[(1, '3x3x3 キューブ'), (2, '2x2x2 キューブ'), (3, '4x4x4 キューブ'), (4, '5x5x5 キューブ'), (5, '6x6x6 キューブ'), (6, '7x7x7 キューブ'), (7, '3x3x3 目隠し'), (8, '3x3x3 最少手数'), (9, '3x3x3 片手'), (10, 'クロック'), (11, 'メガミンクス'), (12, 'ピラミンクス'), (13, 'スキューブ'), (14, 'スクエア1'), (15, '4x4x4 目隠し'), (16, '5x5x5 目隠し'), (17, '3x3x3 複数目隠し')], verbose_name='イベントID'),
        ),
    ]
