# Generated by Django 2.2.12 on 2020-12-20 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201220_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='regional_average_id',
        ),
        migrations.RemoveField(
            model_name='result',
            name='regional_best_id',
        ),
    ]
