# Generated by Django 2.2.24 on 2021-06-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210627_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name='メールアドレス'),
        ),
    ]
