# Generated by Django 2.2.24 on 2021-06-30 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_competition_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='twin_competition_id',
            field=models.IntegerField(default=0, verbose_name='双子大会ID'),
        ),
    ]
