# Generated by Django 2.2.12 on 2020-12-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201220_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagerank',
            name='year',
            field=models.SmallIntegerField(default=0, verbose_name='年'),
        ),
        migrations.AddField(
            model_name='bestrank',
            name='year',
            field=models.SmallIntegerField(default=0, verbose_name='年'),
        ),
        migrations.AlterField(
            model_name='averagerank',
            name='best',
            field=models.FloatField(verbose_name='ベスト'),
        ),
        migrations.AlterField(
            model_name='bestrank',
            name='best',
            field=models.FloatField(verbose_name='ベスト'),
        ),
    ]
