# Generated by Django 2.2.24 on 2021-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_competition_twin_competition_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competitor",
            name="guest_count",
            field=models.SmallIntegerField(verbose_name="同伴者数"),
        ),
    ]
