# Generated by Django 2.2.12 on 2020-12-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20201227_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagerank',
            name='national_rank',
        ),
        migrations.RemoveField(
            model_name='averagerank',
            name='prefecture_rank',
        ),
        migrations.RemoveField(
            model_name='bestrank',
            name='national_rank',
        ),
        migrations.RemoveField(
            model_name='bestrank',
            name='prefecture_rank',
        ),
        migrations.AddField(
            model_name='averagerank',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男性'), (2, '女性')], default=0, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='averagerank',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='ランク'),
        ),
        migrations.AddField(
            model_name='bestrank',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男性'), (2, '女性')], default=0, verbose_name='性別'),
        ),
        migrations.AddField(
            model_name='bestrank',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='ランク'),
        ),
    ]
