# Generated by Django 2.2.12 on 2021-04-20 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201230_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='fee',
        ),
        migrations.AddField(
            model_name='person',
            name='wca_user_id',
            field=models.IntegerField(default=0, verbose_name='WCA_USER_ID'),
        ),
        migrations.AlterField(
            model_name='information',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='公開する'),
        ),
    ]
