# Generated by Django 2.2.12 on 2021-04-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210420_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePerEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.IntegerField(verbose_name='大会ID')),
                ('event_id', models.SmallIntegerField(choices=[(1, '3x3x3 キューブ'), (2, '2x2x2 キューブ'), (3, '4x4x4 キューブ'), (4, '5x5x5 キューブ'), (5, '6x6x6 キューブ'), (6, '7x7x7 キューブ'), (7, '3x3x3 目隠し'), (8, '3x3x3 最少手数'), (9, '3x3x3 片手'), (10, 'クロック'), (11, 'メガミンクス'), (12, 'ピラミンクス'), (13, 'スキューブ'), (14, 'スクエア1'), (15, '4x4x4 目隠し'), (16, '5x5x5 目隠し'), (17, '3x3x3 複数目隠し')], verbose_name='イベントID')),
                ('price', models.IntegerField(verbose_name='料金')),
            ],
        ),
        migrations.CreateModel(
            name='FeePerEventCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_id', models.IntegerField(verbose_name='大会ID')),
                ('event_count', models.SmallIntegerField(verbose_name='イベント数')),
                ('price', models.IntegerField(verbose_name='料金')),
            ],
        ),
        migrations.AddField(
            model_name='competition',
            name='fee_calc_type',
            field=models.SmallIntegerField(choices=[(1, '種目別'), (2, '種目数')], default=0, verbose_name='参加費計算タイプ'),
        ),
        migrations.AddField(
            model_name='competition',
            name='fee_pay_type',
            field=models.SmallIntegerField(choices=[(1, '現地支払'), (2, '事前支払または現地支払'), (3, '事前支払')], default=0, verbose_name='参加費支払いタイプ'),
        ),
        migrations.AddField(
            model_name='competition',
            name='type',
            field=models.SmallIntegerField(choices=[(1, 'SCJ大会'), (2, 'WCA大会')], default=0, verbose_name='大会タイプ'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='stripe_id',
            field=models.CharField(default='', max_length=256, verbose_name='Stripe決済ID'),
        ),
    ]
