# Generated by Django 2.2.12 on 2021-04-24 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210422_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='attempt_count',
            field=models.SmallIntegerField(default=0, verbose_name='挑戦回数'),
        ),
        migrations.AddField(
            model_name='round',
            name='cutoff_attempt_count',
            field=models.SmallIntegerField(default=0, verbose_name='カットオフ回数'),
        ),
        migrations.AddField(
            model_name='round',
            name='limit_type',
            field=models.SmallIntegerField(choices=[(1, '時間制限'), (2, '累計時間制限')], default=0, verbose_name='制限タイプ'),
        ),
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '予選'), (2, '2次予選'), (3, '準決勝'), (4, '決勝'), (5, '複合予選'), (6, '複合2次予選'), (7, '複合決勝')], verbose_name='ラウンドタイプ'),
        ),
    ]
