# Generated by Django 2.2.24 on 2021-07-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210703_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_event_offerer',
            field=models.BooleanField(default=False, verbose_name='イベント申請者フラグ'),
        ),
    ]
