# Generated by Django 2.2.12 on 2021-04-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210424_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wca_name',
            field=models.CharField(default='', max_length=256, verbose_name='WCA氏名'),
        ),
    ]
