# Generated by Django 2.2.12 on 2021-04-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_person_wca_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagerank',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='averagerank',
            name='prefecture_id',
        ),
        migrations.RemoveField(
            model_name='bestrank',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='bestrank',
            name='prefecture_id',
        ),
        migrations.AddField(
            model_name='averagerank',
            name='gender_rank',
            field=models.IntegerField(default=0, verbose_name='性別ランク'),
        ),
        migrations.AddField(
            model_name='averagerank',
            name='generation_rank',
            field=models.IntegerField(default=0, verbose_name='世代ランク'),
        ),
        migrations.AddField(
            model_name='averagerank',
            name='prefecture_rank',
            field=models.IntegerField(default=0, verbose_name='県ランク'),
        ),
        migrations.AddField(
            model_name='bestrank',
            name='gender_rank',
            field=models.IntegerField(default=0, verbose_name='性別ランク'),
        ),
        migrations.AddField(
            model_name='bestrank',
            name='generation_rank',
            field=models.IntegerField(default=0, verbose_name='世代ランク'),
        ),
        migrations.AddField(
            model_name='bestrank',
            name='prefecture_rank',
            field=models.IntegerField(default=0, verbose_name='県ランク'),
        ),
    ]
