# Generated by Django 2.2.24 on 2021-07-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210710_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='venue_url',
            field=models.CharField(default='', max_length=256, verbose_name='開催地URL'),
        ),
    ]
