# Generated by Django 2.2.12 on 2021-04-30 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210430_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averagerank',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='bestrank',
            name='person_id',
        ),
        migrations.AddField(
            model_name='averagerank',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
        migrations.AddField(
            model_name='bestrank',
            name='person',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Person'),
        ),
    ]
