# Generated by Django 2.2.24 on 2021-07-13 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_competition_venue_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='email',
            new_name='organizer_email',
        ),
    ]
