# Generated by Django 2.2.12 on 2021-04-30 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210430_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='averagerank',
            name='competition_name_id',
            field=models.CharField(default='', max_length=64, verbose_name='大会名ID'),
        ),
        migrations.AddField(
            model_name='averagerank',
            name='value1',
            field=models.FloatField(default=0, verbose_name='値1'),
        ),
        migrations.AddField(
            model_name='averagerank',
            name='value2',
            field=models.FloatField(default=0, verbose_name='値2'),
        ),
        migrations.AddField(
            model_name='averagerank',
            name='value3',
            field=models.FloatField(default=0, verbose_name='値3'),
        ),
        migrations.AddField(
            model_name='averagerank',
            name='value4',
            field=models.FloatField(default=0, verbose_name='値4'),
        ),
        migrations.AddField(
            model_name='averagerank',
            name='value5',
            field=models.FloatField(default=0, verbose_name='値5'),
        ),
        migrations.AddField(
            model_name='bestrank',
            name='competition_name_id',
            field=models.CharField(default='', max_length=64, verbose_name='大会名ID'),
        ),
        migrations.AlterField(
            model_name='averagerank',
            name='event_id',
            field=models.SmallIntegerField(choices=[(1, '3x3x3 キューブ'), (2, '2x2x2 キューブ'), (3, '4x4x4 キューブ'), (4, '5x5x5 キューブ'), (5, '6x6x6 キューブ'), (6, '7x7x7 キューブ'), (7, '3x3x3 目隠し'), (8, '3x3x3 最少手数'), (9, '3x3x3 片手'), (10, 'クロック'), (11, 'メガミンクス'), (12, 'ピラミンクス'), (13, 'スキューブ'), (14, 'スクエア1'), (15, '4x4x4 目隠し'), (16, '5x5x5 目隠し'), (17, '3x3x3 複数目隠し')], db_index=True, verbose_name='イベントID'),
        ),
        migrations.AlterField(
            model_name='averagerank',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男性'), (2, '女性')], db_index=True, default=0, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='averagerank',
            name='generation',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='世代'),
        ),
        migrations.AlterField(
            model_name='averagerank',
            name='prefecture_id',
            field=models.SmallIntegerField(choices=[(1, '北海道'), (2, '青森県'), (3, '岩手県'), (4, '宮城県'), (5, '秋田県'), (6, '山形県'), (7, '福島県'), (8, '茨城県'), (9, '栃木県'), (10, '群馬県'), (11, '埼玉県'), (12, '千葉県'), (13, '東京都'), (14, '神奈川県'), (15, '新潟県'), (16, '富山県'), (17, '石川県'), (18, '福井県'), (19, '山梨県'), (20, '長野県'), (21, '岐阜県'), (22, '静岡県'), (23, '愛知県'), (24, '三重県'), (25, '滋賀県'), (26, '京都府'), (27, '大阪府'), (28, '兵庫県'), (29, '奈良県'), (30, '和歌山県'), (31, '鳥取県'), (32, '島根県'), (33, '岡山県'), (34, '広島県'), (35, '山口県'), (36, '徳島県'), (37, '香川県'), (38, '愛媛県'), (39, '高知県'), (40, '福岡県'), (41, '佐賀県'), (42, '長崎県'), (43, '熊本県'), (44, '大分県'), (45, '宮崎県'), (46, '鹿児島'), (47, '沖縄県'), (48, '海外')], db_index=True, default=0, verbose_name='都道府県ID'),
        ),
        migrations.AlterField(
            model_name='bestrank',
            name='event_id',
            field=models.SmallIntegerField(choices=[(1, '3x3x3 キューブ'), (2, '2x2x2 キューブ'), (3, '4x4x4 キューブ'), (4, '5x5x5 キューブ'), (5, '6x6x6 キューブ'), (6, '7x7x7 キューブ'), (7, '3x3x3 目隠し'), (8, '3x3x3 最少手数'), (9, '3x3x3 片手'), (10, 'クロック'), (11, 'メガミンクス'), (12, 'ピラミンクス'), (13, 'スキューブ'), (14, 'スクエア1'), (15, '4x4x4 目隠し'), (16, '5x5x5 目隠し'), (17, '3x3x3 複数目隠し')], db_index=True, verbose_name='イベントID'),
        ),
        migrations.AlterField(
            model_name='bestrank',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男性'), (2, '女性')], db_index=True, default=0, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='bestrank',
            name='generation',
            field=models.SmallIntegerField(db_index=True, default=0, verbose_name='世代'),
        ),
        migrations.AlterField(
            model_name='bestrank',
            name='prefecture_id',
            field=models.SmallIntegerField(choices=[(1, '北海道'), (2, '青森県'), (3, '岩手県'), (4, '宮城県'), (5, '秋田県'), (6, '山形県'), (7, '福島県'), (8, '茨城県'), (9, '栃木県'), (10, '群馬県'), (11, '埼玉県'), (12, '千葉県'), (13, '東京都'), (14, '神奈川県'), (15, '新潟県'), (16, '富山県'), (17, '石川県'), (18, '福井県'), (19, '山梨県'), (20, '長野県'), (21, '岐阜県'), (22, '静岡県'), (23, '愛知県'), (24, '三重県'), (25, '滋賀県'), (26, '京都府'), (27, '大阪府'), (28, '兵庫県'), (29, '奈良県'), (30, '和歌山県'), (31, '鳥取県'), (32, '島根県'), (33, '岡山県'), (34, '広島県'), (35, '山口県'), (36, '徳島県'), (37, '香川県'), (38, '愛媛県'), (39, '高知県'), (40, '福岡県'), (41, '佐賀県'), (42, '長崎県'), (43, '熊本県'), (44, '大分県'), (45, '宮崎県'), (46, '鹿児島'), (47, '沖縄県'), (48, '海外')], db_index=True, default=0, verbose_name='都道府県ID'),
        ),
    ]
