# Generated by Django 2.2.24 on 2021-07-14 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_auto_20210714_0059"),
    ]

    operations = [
        migrations.AlterField(
            model_name="competition",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
