# Generated by Django 2.2.12 on 2021-05-06 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210430_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='stripe_user_person_id',
            field=models.IntegerField(default=0, verbose_name='Stripe使用者ID'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_judge',
            field=models.BooleanField(default=False, verbose_name='審判員フラグ'),
        ),
        migrations.AddField(
            model_name='person',
            name='stripe_user_id',
            field=models.CharField(default='', max_length=256, verbose_name='STRIPE_USER_ID'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wca_id',
            field=models.CharField(max_length=10, verbose_name='WCA_ID'),
        ),
    ]
