# Generated by Django 2.2.24 on 2021-07-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0017_auto_20210714_2235"),
    ]

    operations = [
        migrations.AlterField(
            model_name="round",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
