# Generated by Django 2.2.24 on 2021-10-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210722_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wca_birth_at',
            field=models.DateField(null=True, verbose_name='WCA生年月日'),
        ),
    ]
