# Generated by Django 2.2.12 on 2021-05-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210506_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='stripe_access_token',
            field=models.CharField(default='', max_length=256, verbose_name='STRIPEアクセストークン'),
        ),
        migrations.AddField(
            model_name='person',
            name='stripe_publishable_key',
            field=models.CharField(default='', max_length=256, verbose_name='STRIPE公開鍵'),
        ),
        migrations.AddField(
            model_name='person',
            name='stripe_refresh_token',
            field=models.CharField(default='', max_length=256, verbose_name='STRIPEリフレッシュトークン'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wca_access_token',
            field=models.CharField(max_length=256, verbose_name='WCAアクセストークン'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wca_refresh_token',
            field=models.CharField(max_length=256, verbose_name='WCAリフレッシュトークン'),
        ),
    ]
