# Generated by Django 2.2.24 on 2021-11-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_person_wca_birth_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='disclaimer',
            field=models.TextField(default='', verbose_name='免責事項'),
        ),
        migrations.AddField(
            model_name='competition',
            name='disclaimer_en',
            field=models.TextField(default='', verbose_name='免責事項(英文)'),
        ),
    ]
