# Generated by Django 2.2.12 on 2021-05-06 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210506_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='stripe_access_token',
        ),
        migrations.RemoveField(
            model_name='person',
            name='stripe_publishable_key',
        ),
        migrations.RemoveField(
            model_name='person',
            name='stripe_refresh_token',
        ),
    ]
