# Generated by Django 2.2.24 on 2021-11-21 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20211104_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scramble',
            name='scramble',
            field=models.TextField(verbose_name='スクランブル'),
        ),
    ]
