# Generated by Django 2.2.12 on 2021-05-20 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210515_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='name_id',
            field=models.CharField(max_length=64, verbose_name='大会名ID'),
        ),
        migrations.AlterField(
            model_name='result',
            name='competition_id',
            field=models.IntegerField(verbose_name='大会ID'),
        ),
        migrations.AddIndex(
            model_name='competition',
            index=models.Index(fields=['name_id'], name='idx_name_id'),
        ),
        migrations.AddIndex(
            model_name='competitor',
            index=models.Index(fields=['competition_id', 'person'], name='idx_competition_id_person'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['competition_id'], name='idx_competition_id'),
        ),
    ]
