# Generated by Django 2.2.24 on 2022-03-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20220311_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='requirement_en',
        ),
        migrations.AddField(
            model_name='competition',
            name='awards_description',
            field=models.TextField(default='', verbose_name='参加資格'),
        ),
        migrations.AddField(
            model_name='competition',
            name='awards_description_en',
            field=models.TextField(default='', verbose_name='参加資格(英文)'),
        ),
        migrations.AddField(
            model_name='competition',
            name='qualification_description',
            field=models.TextField(default='', verbose_name='参加資格'),
        ),
        migrations.AddField(
            model_name='competition',
            name='qualification_description_en',
            field=models.TextField(default='', verbose_name='参加資格(英文)'),
        ),
    ]
