# Generated by Django 2.2.12 on 2021-05-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20210520_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_display_pending_competitor',
            field=models.BooleanField(default=False, verbose_name='承認前の競技者の一覧表示フラグ'),
        ),
    ]
