# Generated by Django 2.2.24 on 2022-03-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20220313_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='assignment_description',
            field=models.TextField(default='', verbose_name='表彰'),
        ),
        migrations.AddField(
            model_name='competition',
            name='assignment_description_en',
            field=models.TextField(default='', verbose_name='表彰(英文)'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='awards_description',
            field=models.TextField(default='', verbose_name='表彰'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='awards_description_en',
            field=models.TextField(default='', verbose_name='表彰(英文)'),
        ),
    ]
