# Generated by Django 2.2.12 on 2021-05-22 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20210522_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='pay_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='支払日時'),
        ),
    ]
