# Generated by Django 2.2.24 on 2022-03-27 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20220313_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WcaAverageRank',
        ),
        migrations.DeleteModel(
            name='WcaBestRank',
        ),
    ]
