# Generated by Django 2.2.12 on 2021-05-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_competitor_pay_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='pay_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='支払日時'),
        ),
    ]
