# Generated by Django 2.2.12 on 2021-05-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210522_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='refund_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='返金日時'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='refund_price',
            field=models.IntegerField(default=0, verbose_name='返金額'),
        ),
    ]
