# Generated by Django 2.2.24 on 2022-04-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_competition_is_registration_only_at_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='registration_close_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='申し込み終了日時'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='registration_open_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='申し込み開始日時'),
        ),
    ]
