# Generated by Django 2.2.12 on 2021-05-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_competitor_pay_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='description_ja',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='requirement_en',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='requirement_ja',
        ),
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(default='', verbose_name='大会説明'),
        ),
        migrations.AddField(
            model_name='competition',
            name='requirement',
            field=models.TextField(default='', verbose_name='参加要件'),
        ),
    ]
