# Generated by Django 2.2.24 on 2022-04-21 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20220402_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='registration_url',
            field=models.CharField(default='', max_length=512, verbose_name='外部申込みURL'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='venue_url',
            field=models.CharField(default='', max_length=512, verbose_name='開催地URL'),
        ),
    ]
