# Generated by Django 2.2.12 on 2021-05-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20210523_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='event_name',
            field=models.CharField(default='', max_length=64, verbose_name='イベント名'),
        ),
    ]
