# Generated by Django 2.2.12 on 2021-06-01 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_round_event_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wca_email',
            field=models.EmailField(default='', max_length=254, verbose_name='WCA EMAIL'),
        ),
    ]
