# Generated by Django 2.2.12 on 2021-06-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_person_wca_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='wca_country_iso2',
            field=models.CharField(default='', max_length=2, verbose_name='WCA所属国'),
        ),
    ]
