# Generated by Django 2.2.24 on 2022-06-12 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20220610_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='visitor_description',
            field=models.TextField(default='', verbose_name='見学事項'),
        ),
        migrations.AddField(
            model_name='competition',
            name='visitor_description_en',
            field=models.TextField(default='', verbose_name='見学事項(英文)'),
        ),
    ]
