# Generated by Django 2.2.24 on 2022-06-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20220612_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '一回戦'), (2, '二次予選'), (3, '準決勝'), (4, '決勝')], verbose_name='ラウンドタイプ'),
        ),
    ]
