# Generated by Django 2.2.12 on 2021-06-05 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_person_wca_country_iso2'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=64, verbose_name='Stripe顧客ID')),
                ('competition_id', models.IntegerField(default=0, verbose_name='大会ID')),
                ('competitor_id', models.IntegerField(default=0, verbose_name='選手ID')),
                ('charge_id', models.CharField(default='', max_length=256, verbose_name='Stripe決済ID')),
                ('pay_price', models.IntegerField(default=0, verbose_name='支払額')),
                ('refund_price', models.IntegerField(default=0, verbose_name='返金額')),
                ('pay_at', models.DateTimeField(default=None, verbose_name='支払日時')),
                ('refund_at', models.DateTimeField(default=None, null=True, verbose_name='返金日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='pay_at',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='pay_price',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='refund_at',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='refund_price',
        ),
        migrations.RemoveField(
            model_name='competitor',
            name='stripe_id',
        ),
        migrations.AddIndex(
            model_name='stripeprogress',
            index=models.Index(fields=['customer_id'], name='idx_customer_id'),
        ),
        migrations.AddIndex(
            model_name='stripeprogress',
            index=models.Index(fields=['competitor_id'], name='idx_competitor_id'),
        ),
    ]
