# Generated by Django 2.2.24 on 2022-07-20 14:01

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20220612_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='limit_event_ids',
            field=django_mysql.models.JSONField(default=dict, verbose_name='累積タイム合計種目'),
        ),
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '一回戦'), (2, '二次予選'), (3, '準決勝'), (4, '決勝')], verbose_name='ラウンドタイプ'),
        ),
    ]
