# Generated by Django 2.2.12 on 2021-06-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20210605_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripeprogress',
            name='pay_at',
            field=models.DateTimeField(default=None, null=True, verbose_name='支払日時'),
        ),
    ]
