# Generated by Django 2.2.24 on 2022-07-31 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20220614_2305'),
        ('app', '0033_auto_20220720_2301'),
    ]

    operations = [
    ]
