# Generated by Django 2.2.24 on 2022-09-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_merge_20220731_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='WcaRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wca_id', models.CharField(max_length=10, verbose_name='WCA_ID')),
                ('event_id', models.SmallIntegerField(choices=[(1, '3x3x3 キューブ'), (2, '2x2x2 キューブ'), (3, '4x4x4 キューブ'), (4, '5x5x5 キューブ'), (5, '6x6x6 キューブ'), (6, '7x7x7 キューブ'), (7, '3x3x3 目隠し'), (8, '3x3x3 最少手数'), (9, '3x3x3 片手'), (10, 'クロック'), (11, 'メガミンクス'), (12, 'ピラミンクス'), (13, 'スキューブ'), (14, 'スクエア1'), (15, '4x4x4 目隠し'), (16, '5x5x5 目隠し'), (17, '3x3x3 複数目隠し')], verbose_name='イベントID')),
                ('type', models.SmallIntegerField(choices=[(1, 'SINGLE'), (2, 'AVERAGE')], verbose_name='レコードタイプ')),
                ('best', models.FloatField(verbose_name='ベスト')),
                ('world_rank', models.IntegerField(default=0, verbose_name='世界ランク')),
                ('continent_rank', models.IntegerField(default=0, verbose_name='大陸ランク')),
                ('country_rank', models.IntegerField(default=0, verbose_name='国ランク')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
