# Generated by Django 2.2.12 on 2021-06-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20210612_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='is_payment',
            field=models.BooleanField(default=False, verbose_name='課金可否'),
        ),
    ]
