# Generated by Django 2.2.24 on 2022-09-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_wcarank'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wcarank',
            index=models.Index(fields=['wca_id', 'event_id'], name='idx_wca_id_event_id'),
        ),
    ]
