# Generated by Django 2.2.24 on 2021-06-16 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_competition_is_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'REGISTRATION'), (3, 'CANCEL')], verbose_name='状態'),
        ),
    ]
