# Generated by Django 2.2.24 on 2022-09-17 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20220914_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='round',
        ),
        migrations.RemoveField(
            model_name='scramble',
            name='round_id',
        ),
        migrations.AddField(
            model_name='result',
            name='round_type',
            field=models.SmallIntegerField(choices=[(1, '一回戦'), (2, '二次予選'), (3, '準決勝'), (4, '決勝')], default=0, verbose_name='ラウンドタイプ'),
        ),
        migrations.AddField(
            model_name='scramble',
            name='round_type',
            field=models.SmallIntegerField(choices=[(1, '一回戦'), (2, '二次予選'), (3, '準決勝'), (4, '決勝')], default=0, verbose_name='ラウンドタイプ'),
        ),
    ]
