# Generated by Django 2.2.24 on 2022-10-02 03:47

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_auto_20220917_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='event_limits',
            field=django_mysql.models.JSONField(default=dict, verbose_name='イベント別定員'),
        ),
        migrations.AlterField(
            model_name='result',
            name='round_type',
            field=models.SmallIntegerField(choices=[(1, '一回戦'), (2, '二回戦'), (3, '準決勝'), (4, '決勝')], default=0, verbose_name='ラウンドタイプ'),
        ),
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '一回戦'), (2, '二回戦'), (3, '準決勝'), (4, '決勝')], verbose_name='ラウンドタイプ'),
        ),
        migrations.AlterField(
            model_name='scramble',
            name='round_type',
            field=models.SmallIntegerField(choices=[(1, '一回戦'), (2, '二回戦'), (3, '準決勝'), (4, '決勝')], default=0, verbose_name='ラウンドタイプ'),
        ),
    ]
