# Generated by Django 2.2.24 on 2024-01-14 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20230430_2316'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WcaRank',
        ),
    ]
