# Generated by Django 2.2.24 on 2023-07-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20230430_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='use_reception',
            field=models.BooleanField(default=False, verbose_name='受付システムの使用要否'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='reception_status',
            field=models.SmallIntegerField(choices=[(0, 'NOT_YET_RECEPTION'), (1, 'SELF_RECEPTION'), (2, 'ALL_RECEPTION')], default=0, verbose_name='受付状態'),
        ),
    ]
