# Generated by Django 2.2.24 on 2023-05-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20230430_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='free_visitor_count',
            field=models.SmallIntegerField(default=0, verbose_name='見学者数'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='actual_guest_count',
            field=models.SmallIntegerField(default=0, verbose_name='当日同伴者数'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='reception_status',
            field=models.SmallIntegerField(choices=[(1, 'NOT_YET_RECEPTION'), (2, 'SELF_RECEPTION'), (3, 'ALL_RECEPTION')], default=1, verbose_name='受付状態'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='visitor_count',
            field=models.SmallIntegerField(default=0, verbose_name='見学者数'),
        ),
    ]
