# Generated by Django 2.2.24 on 2023-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20230430_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='round_type',
            field=models.SmallIntegerField(choices=[(1, '一回戦'), (2, '二回戦'), (3, '三回戦'), (4, '決勝')], default=0, verbose_name='ラウンドタイプ'),
        ),
        migrations.AlterField(
            model_name='round',
            name='type',
            field=models.SmallIntegerField(choices=[(1, '一回戦'), (2, '二回戦'), (3, '三回戦'), (4, '決勝')], verbose_name='ラウンドタイプ'),
        ),
        migrations.AlterField(
            model_name='scramble',
            name='round_type',
            field=models.SmallIntegerField(choices=[(1, '一回戦'), (2, '二回戦'), (3, '三回戦'), (4, '決勝')], default=0, verbose_name='ラウンドタイプ'),
        ),
    ]
