# Generated by Django 2.2.24 on 2023-06-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20230527_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='use_reception',
            field=models.BooleanField(default=False, verbose_name='受付システムの使用要否'),
        ),
    ]
