SCJ_COMPETITON_FIRST_YEAR = 2020
PREFECTURE_COUNT = 47
COMPETITOR_STATUS_PENDING = 1
COMPETITOR_STATUS_REGISTRATION = 2
COMPETITOR_STATUS_CANCEL = 3
INFORMATION_TYPE_EVENT = 3
NR_REGIONAL_ID = 99
COMPETITION_TYPE_SCJ = 1
COMPETITION_TYPE_WCA = 2
FEE_CALC_TYPE_EVENT = 1
FEE_CALC_TYPE_EVENT_COUNT = 2
FEE_PAY_TYPE_LOCAL_ONLY = 1
FEE_PAY_TYPE_LOCAL_AND_REMOTE = 2
FEE_PAY_TYPE_REMOTE_ONLY = 3
ROUND_LIMIT_TYPE_LIMIT = 1
ROUND_LIMIT_TYPE_CUMULATIVE = 2
EVENT_ID_FMC = 8
GENERATION_MAX = 10
EVENT_ONLY_BEST_IDS = [15, 16, 17]
OUTLIERS = 99999999999

COMPETITOR_STATUS = (
    (1, '未承認'),
    (2, '承認'),
)

INFORMATION_TYPE = (
    (1, 'WCA大会'),
    (2, 'SCJ大会'),
    (3, 'イベント'),
    (4, 'お知らせ'),
)

INFORMATION_TYPE_EN = (
    ('wca_competition', 1),
    ('scj_competition', 2),
    ('event', 3),
    ('information', 4),
)

GENDER = (
    (1, '男性'),
    (2, '女性'),
)

GENDER_EN = (
    (1, 'm'),
    (2, 'f'),
)

COMPETITION_TYPE = (
    (1, 'SCJ大会'),
    (2, 'WCA大会'),
)

FEE_PAY_TYPE = (
    (1, '現地支払'),
    (2, '事前支払または現地支払'),
    (3, '事前支払'),
)

FEE_CALC_TYPE = (
    (1, '種目別'),
    (2, '種目数'),
)

PREFECTURE = (
    (1, '北海道'),
    (2, '青森県'),
    (3, '岩手県'),
    (4, '宮城県'),
    (5, '秋田県'),
    (6, '山形県'),
    (7, '福島県'),
    (8, '茨城県'),
    (9, '栃木県'),
    (10, '群馬県'),
    (11, '埼玉県'),
    (12, '千葉県'),
    (13, '東京都'),
    (14, '神奈川県'),
    (15, '新潟県'),
    (16, '富山県'),
    (17, '石川県'),
    (18, '福井県'),
    (19, '山梨県'),
    (20, '長野県'),
    (21, '岐阜県'),
    (22, '静岡県'),
    (23, '愛知県'),
    (24, '三重県'),
    (25, '滋賀県'),
    (26, '京都府'),
    (27, '大阪府'),
    (28, '兵庫県'),
    (29, '奈良県'),
    (30, '和歌山県'),
    (31, '鳥取県'),
    (32, '島根県'),
    (33, '岡山県'),
    (34, '広島県'),
    (35, '山口県'),
    (36, '徳島県'),
    (37, '香川県'),
    (38, '愛媛県'),
    (39, '高知県'),
    (40, '福岡県'),
    (41, '佐賀県'),
    (42, '長崎県'),
    (43, '熊本県'),
    (44, '大分県'),
    (45, '宮崎県'),
    (46, '鹿児島'),
    (47, '沖縄県'),
    (48, '海外'),
)

FORMAT = (
    (1, 'Best of 1'),
    (2, 'Best of 2'),
    (3, 'Best of 3'),
    (4, 'Average of 5'),
    (5, 'Mean of 3'),
)

ROUND_TYPE = (
    (1, '予選'),
    (2, '2次予選'),
    (3, '準決勝'),
    (4, '決勝'),
    (5, '複合予選'),
    (6, '複合2次予選'),
    (7, '複合決勝'),
)

ROUND_LIMIT_TYPE = (
    (1, '時間制限'),
    (2, '累計時間制限'),
)

REGIONAL_RECORD = (
    (1, "PR"),
    (2, "NR"),
)

EVENT = (
    (1, "3x3x3 キューブ"),
    (2, "2x2x2 キューブ"),
    (3, "4x4x4 キューブ"),
    (4, "5x5x5 キューブ"),
    (5, "6x6x6 キューブ"),
    (6, "7x7x7 キューブ"),
    (7, "3x3x3 目隠し"),
    (8, "3x3x3 最少手数"),
    (9, "3x3x3 片手"),
    (10, "クロック"),
    (11, "メガミンクス"),
    (12, "ピラミンクス"),
    (13, "スキューブ"),
    (14, "スクエア1"),
    (15, "4x4x4 目隠し"),
    (16, "5x5x5 目隠し"),
    (17, "3x3x3 複数目隠し"),
)

EVENT_ID_NAME = (
    (1, "333"),
    (2, "222"),
    (3, "444"),
    (4, "555"),
    (5, "666"),
    (6, "777"),
    (7, "333bf"),
    (8, "333fm"),
    (9, "333oh"),
    (10, "clock"),
    (11, "minx"),
    (12, "pyram"),
    (13, "skewb"),
    (14, "sq1"),
    (15, "444bf"),
    (16, "555bf"),
    (17, "333mbf"),
)

COUNTRY = (
    ('AF', 'Afghanistan'),
    ('AL', 'Albania'),
    ('DZ', 'Algeria'),
    ('AD', 'Andorra'),
    ('AO', 'Angola'),
    ('AG', 'AntiguaandBarbuda'),
    ('AR', 'Argentina'),
    ('AM', 'Armenia'),
    ('AU', 'Australia'),
    ('AT', 'Austria'),
    ('AZ', 'Azerbaijan'),
    ('BS', 'Bahamas'),
    ('BH', 'Bahrain'),
    ('BD', 'Bangladesh'),
    ('BB', 'Barbados'),
    ('BY', 'Belarus'),
    ('BE', 'Belgium'),
    ('BZ', 'Belize'),
    ('BJ', 'Benin'),
    ('BT', 'Bhutan'),
    ('BO', 'Bolivia'),
    ('BA', 'BosniaandHerzegovina'),
    ('BW', 'Botswana'),
    ('BR', 'Brazil'),
    ('BN', 'Brunei'),
    ('BG', 'Bulgaria'),
    ('BF', 'BurkinaFaso'),
    ('BI', 'Burundi'),
    ('CV', 'CaboVerde'),
    ('KH', 'Cambodia'),
    ('CM', 'Cameroon'),
    ('CA', 'Canada'),
    ('CF', 'CentralAfricanRepublic'),
    ('TD', 'Chad'),
    ('CL', 'Chile'),
    ('CN', 'China'),
    ('CO', 'Colombia'),
    ('KM', 'Comoros'),
    ('CG', 'Congo'),
    ('CR', 'CostaRica'),
    ('CI', 'Coted_Ivoire'),
    ('HR', 'Croatia'),
    ('CU', 'Cuba'),
    ('CY', 'Cyprus'),
    ('CZ', 'CzechRepublic'),
    ('KP', 'DemocraticPeople_sRepublicofKorea'),
    ('CD', 'DemocraticRepublicoftheCongo'),
    ('DK', 'Denmark'),
    ('DJ', 'Djibouti'),
    ('DM', 'Dominica'),
    ('DO', 'DominicanRepublic'),
    ('EC', 'Ecuador'),
    ('EG', 'Egypt'),
    ('SV', 'ElSalvador'),
    ('GQ', 'EquatorialGuinea'),
    ('ER', 'Eritrea'),
    ('EE', 'Estonia'),
    ('SZ', 'Eswatini'),
    ('ET', 'Ethiopia'),
    ('FM', 'FederatedStatesofMicronesia'),
    ('FJ', 'Fiji'),
    ('FI', 'Finland'),
    ('FR', 'France'),
    ('GA', 'Gabon'),
    ('GM', 'Gambia'),
    ('GE', 'Georgia'),
    ('DE', 'Germany'),
    ('GH', 'Ghana'),
    ('GR', 'Greece'),
    ('GD', 'Grenada'),
    ('GT', 'Guatemala'),
    ('GN', 'Guinea'),
    ('GW', 'GuineaBissau'),
    ('GY', 'Guyana'),
    ('HT', 'Haiti'),
    ('HN', 'Honduras'),
    ('HK', 'HongKong'),
    ('HU', 'Hungary'),
    ('IS', 'Iceland'),
    ('IN', 'India'),
    ('ID', 'Indonesia'),
    ('IR', 'Iran'),
    ('IQ', 'Iraq'),
    ('IE', 'Ireland'),
    ('IL', 'Israel'),
    ('IT', 'Italy'),
    ('JM', 'Jamaica'),
    ('JP', 'Japan'),
    ('JO', 'Jordan'),
    ('KZ', 'Kazakhstan'),
    ('KE', 'Kenya'),
    ('KI', 'Kiribati'),
    ('KR', 'Korea'),
    ('XK', 'Kosovo'),
    ('KW', 'Kuwait'),
    ('KG', 'Kyrgyzstan'),
    ('LA', 'Laos'),
    ('LV', 'Latvia'),
    ('LB', 'Lebanon'),
    ('LS', 'Lesotho'),
    ('LR', 'Liberia'),
    ('LY', 'Libya'),
    ('LI', 'Liechtenstein'),
    ('LT', 'Lithuania'),
    ('LU', 'Luxembourg'),
    ('MO', 'Macau'),
    ('MG', 'Madagascar'),
    ('MW', 'Malawi'),
    ('MY', 'Malaysia'),
    ('MV', 'Maldives'),
    ('ML', 'Mali'),
    ('MT', 'Malta'),
    ('MH', 'MarshallIslands'),
    ('MR', 'Mauritania'),
    ('MU', 'Mauritius'),
    ('MX', 'Mexico'),
    ('MD', 'Moldova'),
    ('MC', 'Monaco'),
    ('MN', 'Mongolia'),
    ('ME', 'Montenegro'),
    ('MA', 'Morocco'),
    ('MZ', 'Mozambique'),
    ('MM', 'Myanmar'),
    ('NA', 'Namibia'),
    ('NR', 'Nauru'),
    ('NP', 'Nepal'),
    ('NL', 'Netherlands'),
    ('NZ', 'NewZealand'),
    ('NI', 'Nicaragua'),
    ('NE', 'Niger'),
    ('NG', 'Nigeria'),
    ('MK', 'NorthMacedonia'),
    ('NO', 'Norway'),
    ('OM', 'Oman'),
    ('PK', 'Pakistan'),
    ('PW', 'Palau'),
    ('PS', 'Palestine'),
    ('PA', 'Panama'),
    ('PG', 'PapuaNewGuinea'),
    ('PY', 'Paraguay'),
    ('PE', 'Peru'),
    ('PH', 'Philippines'),
    ('PL', 'Poland'),
    ('PT', 'Portugal'),
    ('QA', 'Qatar'),
    ('RO', 'Romania'),
    ('RU', 'Russia'),
    ('RW', 'Rwanda'),
    ('KN', 'SaintKittsandNevis'),
    ('LC', 'SaintLucia'),
    ('VC', 'SaintVincentandtheGrenadines'),
    ('WS', 'Samoa'),
    ('SM', 'SanMarino'),
    ('ST', 'SaoTomeandPrincipe'),
    ('SA', 'SaudiArabia'),
    ('SN', 'Senegal'),
    ('RS', 'Serbia'),
    ('SC', 'Seychelles'),
    ('SL', 'SierraLeone'),
    ('SG', 'Singapore'),
    ('SK', 'Slovakia'),
    ('SI', 'Slovenia'),
    ('SB', 'SolomonIslands'),
    ('SO', 'Somalia'),
    ('ZA', 'SouthAfrica'),
    ('SS', 'SouthSudan'),
    ('ES', 'Spain'),
    ('LK', 'SriLanka'),
    ('SD', 'Sudan'),
    ('SR', 'Suriname'),
    ('SE', 'Sweden'),
    ('CH', 'Switzerland'),
    ('SY', 'Syria'),
    ('TW', 'Taiwan'),
    ('TJ', 'Tajikistan'),
    ('TZ', 'Tanzania'),
    ('TH', 'Thailand'),
    ('TL', 'Timor-Leste'),
    ('TG', 'Togo'),
    ('TO', 'Tonga'),
    ('TT', 'TrinidadandTobago'),
    ('TN', 'Tunisia'),
    ('TR', 'Turkey'),
    ('TM', 'Turkmenistan'),
    ('TV', 'Tuvalu'),
    ('UG', 'Uganda'),
    ('UA', 'Ukraine'),
    ('AE', 'UnitedArabEmirates'),
    ('GB', 'UnitedKingdom'),
    ('UY', 'Uruguay'),
    ('US', 'USA'),
    ('UZ', 'Uzbekistan'),
    ('VU', 'Vanuatu'),
    ('VA', 'VaticanCity'),
    ('VE', 'Venezuela'),
    ('VN', 'Vietnam'),
    ('XA', 'XA'),
    ('XE', 'XE'),
    ('XF', 'XF'),
    ('XM', 'XM'),
    ('XN', 'XN'),
    ('XO', 'XO'),
    ('XS', 'XS'),
    ('XW', 'XW'),
    ('YE', 'Yemen'),
    ('ZM', 'Zambia'),
    ('ZW', 'Zimbabwe'),
)